name: MCArcade Splegg
version: 1.6
main: com.raptorhosting.splegg.Splegg
authors: [TheAnimatedduck]
description: Splegg > Spleef using eggs
softdepend: [WorldEdit]
commands:
  splegg:
    description:
    aliases: [sp]
